function [detectors, tracker] = sensors()
%SENSORS  Multi-sensor setup per PS: monocamera + long-range radar -> GNN tracker.
%   Mirrors perception/infer.py (detector list) + perception/tracker.py (KF tracks).
%   Automated Driving Toolbox + Sensor Fusion and Tracking Toolbox required.
    % Camera: 60 deg FOV, 30 Hz, Indian-road classes incl. auto-rickshaw/pedestrian
    cam = visionDetectionGenerator('SensorIndex', 1, ...
        'SensorLocation', [1.4 0], 'Height', 1.3, ...
        'Yaw', 0, 'Pitch', 0, 'FieldOfView', [60 35], ...
        'ImageSize', [640 480], 'DetectionProbability', 0.9, ...
        'FalseAlarmRate', 1e-6, 'ActorProfiles', actorProfiles());
    % Radar: long range for TTC / highway merge (S3)
    rad = radarDetectionGenerator('SensorIndex', 2, ...
        'SensorLocation', [2.0 0], 'Height', 0.6, ...
        'FieldOfView', [20 5], 'RangeLimits', [1 150], ...
        'DetectionProbability', 0.95, 'FalseAlarmRate', 1e-7, ...
        'ActorProfiles', actorProfiles());
    detectors = {cam, rad};
    % GNN multi-object tracker: assignment gate ~= 60 px, 10-frame coast
    % (same semantics as perception/tracker.py max_age=10)
    tracker = multiObjectTracker('FilterInitializationFcn', @initCVKF, ...
        'AssignmentThreshold', 60, 'DeletionThreshold', [10 10], ...
        'ConfirmationThreshold', [2 3]);
end

function p = actorProfiles()
% Footprints matching sim/DIMENSIONS (m): car, auto, truck, bike, ped, cow.
    p = struct('ID', {1 2 3 4 5 6}, ...
        'ClassID', {1 4 6 2 0 4}, ...
        'Length', {4.2 3.0 8.0 2.0 0.6 2.0}, ...
        'Width', {1.8 1.4 2.4 0.7 0.6 1.2}, ...
        'Height', {1.5 1.8 3.0 1.4 1.8 1.5}, ...
        'OriginOffset', {[-1.4 0 0] [-1 0 0] [-2.5 0 0] [-0.6 0 0] [0 0 0] [0 0 0]});
end

function kf = initCVKF(detection)
% Constant-velocity KF, 20 Hz (dt=0.05) — same units as perception/tracker.py.
    dt = 0.05;
    A = [1 0 dt 0; 0 1 0 dt; 0 0 1 0; 0 0 0 1];
    H = [1 0 0 0; 0 1 0 0];
    kf = trackingKF('MotionModel', 'Custom', 'StateTransitionModel', A, ...
        'MeasurementModel', H, 'State', [detection.Measurement; 0; 0], ...
        'StateCovariance', diag([100 100 25 25]), ...
        'ProcessNoise', diag([0.1 0.1 1 1]), 'MeasurementNoise', eye(2));
end
